# Site settings
baseurl = "http://marcorighini.net" #without ending slash
languageCode = "en-us"
theme = "hugo-identity-theme"
title = "Marco Righini - Software Engineer"

# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXX-Y"

[params]

	# Images settings
	# Icons, backgrounds and avatars folders are placed in theme's static/images folder.
	# You may place your images in corresponding folders and then set only filenames below to
	# change page's appearance

	favicon = ""#"favicon.ico"
	appletouchicon = ""#"apple-touch-icon-precomposed.png"
	background = "bg3.jpg"
	avatar = "marco.jpg"

	# Personal settings

  name = "Marco Righini"
	position = "Software Engineer"

	# Extra stuff
	# NOTE: There is little different extra stuff in original Identity theme by HTML5 UP.
	# You can play with it downloading original theme right here:
	# html5up.net/identity/download
	#
	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
	  # - enable form by setting 'enable' to 'true'
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

	email = "mr@marcorighini.net"

	# Contact form settings

	[params.contact]
		enable = false
		formTitle = "Contact Me!"
		namePlaceholder = "Name"
		emailPlaceholder = "Email"
		messagePlaceholder = "Message"
		buttonText = "Send it"

	# Social settings
	# You may change these with your social links or add others

	[[params.social]]
		title = "Email"
		icon = "fa-envelope"
		link = "mailto:mr@marcorighini.net"

	[[params.social]]
		title = "GitHub"
		icon = "fa-github"
		link = "https://github.com/marcorighini"

	[[params.social]]
		title = "LinkedIn"
		icon = "fa-linkedin"
		link = "https://it.linkedin.com/in/righinimarco"

	[[params.social]]
		title = "Twitter"
		icon = "fa-twitter"
		link = "https://twitter.com/mrighini88"

	[[params.social]]
		title = "SlideShare"
		icon = "fa-slideshare"
		link = "http://www.slideshare.net/MarcoRighini1/presentations"


	# Footer settings
	[params.footer]
		copyright = "Marco Righini"
